Repository hmrc/charities-registration-frontend, pull requests merged in 2020-06, with the labels that each got.

#51 DDCE-605: navigation and data reset changes
  app/controllers/IndexController.scala
  app/controllers/charityInformation/CharityContactDetailsController.scala
  app/controllers/charityInformation/CharityNameController.scala
  app/controllers/charityInformation/CharityUKAddressController.scala
  app/controllers/charityInformation/IsCharityOfficialAddressInUKController.scala
  app/controllers/regulatorsAndDocuments/CharityCommissionRegistrationNumberController.scala
  app/controllers/regulatorsAndDocuments/CharityOtherRegulatorDetailsController.scala
  app/controllers/regulatorsAndDocuments/CharityRegulatorController.scala
  app/controllers/regulatorsAndDocuments/GoverningDocumentSummaryController.scala
  app/controllers/regulatorsAndDocuments/IsCharityRegulatorController.scala
  app/controllers/regulatorsAndDocuments/NIRegulatorRegNumberController.scala
  app/controllers/regulatorsAndDocuments/ScottishRegulatorRegNumberController.scala
  app/controllers/regulatorsAndDocuments/SelectWhyNoRegulatorController.scala
  app/controllers/regulatorsAndDocuments/WhyNotRegisteredWithCharityController.scala
  app/models/UserAnswers.scala
  app/navigation/RegulatorsAndDocumentsNavigator.scala
  app/pages/regulatorsAndDocuments/CharityRegulatorPage.scala
  app/pages/sections/Section1Page.scala
  app/pages/sections/Section2Page.scala
  app/pages/sections/Section3Page.scala
  app/pages/sections/Section4Page.scala
  app/queries/Query.scala
  build.sbt
  test/navigation/RegulatorsAndDocumentsNavigatorSpec.scala
  test/pages/regulatorsAndDocuments/CharityRegulatorPageSpec.scala
Labels: Approved

#53 Ddce 604
  app/controllers/regulatorsAndDocuments/SelectWhyNoRegulatorController.scala
  app/navigation/RegulatorsAndDocumentsNavigator.scala
  app/pages/regulatorsAndDocuments/SelectWhyNoRegulatorPage.scala
  app/viewmodels/regulatorsAndDocuments/GoverningDocumentSummaryHelper.scala
  conf/regulatorsAndDocuments.routes
  test/controllers/regulatorsAndDocuments/GoverningDocumentSummaryControllerSpec.scala
  test/controllers/regulatorsAndDocuments/SelectWhyNoRegulatorControllerSpec.scala
  test/navigation/RegulatorsAndDocumentsNavigatorSpec.scala
  test/pages/regulatorsAndDocuments/SelectWhyNoRegulatorPageSpec.scala
  test/viewModels/regulatorsAndDocuments/GoverningDocumentSummaryHelperSpec.scala
Labels: Reviewing

#59 DDCE-670: Refactor generators used in unit tests for charities-registration-frontend
  app/controllers/charityInformation/CharityContactDetailsController.scala
  app/controllers/charityInformation/CharityNameController.scala
  app/forms/regulatorsAndDocuments/CharityOtherRegulatorDetailsFormProvider.scala
  app/repositories/AbstractRepository.scala
  app/repositories/SessionRepository.scala
  app/repositories/UserAnswerRepository.scala
  app/utils/JsonUtils.scala
  app/utils/MessageOption.scala
  app/utils/SessionUtils.scala
  app/viewmodels/regulatorsAndDocuments/RegulatorsSummaryHelper.scala
  build.sbt
  test/forms/behaviours/BooleanFieldBehaviours.scala
  test/forms/behaviours/DateBehaviours.scala
  test/forms/behaviours/FieldBehaviours.scala
  test/forms/behaviours/IntFieldBehaviours.scala
  test/forms/behaviours/OptionFieldBehaviours.scala
  test/forms/behaviours/StringFieldBehaviours.scala
  test/forms/charityInformation/CharityContactDetailsFormProviderSpec.scala
  test/forms/charityInformation/CharityNameFormProviderSpec.scala
  test/forms/mappings/ConstraintsSpec.scala
  test/forms/mappings/DateMappingsSpec.scala
  test/forms/regulatorsAndDocuments/CharityCommissionRegistrationNumberFormProviderSpec.scala
  test/forms/regulatorsAndDocuments/CharityOtherRegulatorDetailsFormProviderSpec.scala
  test/forms/regulatorsAndDocuments/NIRegulatorRegNumberFormProviderSpec.scala
  test/forms/regulatorsAndDocuments/ScottishRegulatorRegNumberFormProviderSpec.scala
  test/forms/regulatorsAndDocuments/WhyNotRegisteredWithCharityFormProviderSpec.scala
  test/generators/ModelGenerators.scala
  test/generators/PageGenerators.scala
  test/generators/UserAnswersEntryGenerators.scala
  test/generators/UserAnswersGenerator.scala
  test/models/UserAnswersSpec.scala
  test/models/regulators/CharityRegulatorSpec.scala
  test/pages/behaviours/PageBehaviours.scala
  test/pages/charityInformation/CharityNamePageSpec.scala
  test/pages/checkEligibility/InEligiblePageSpec.scala
  test/pages/regulatorsAndDocuments/CharityOtherRegulatorDetailsPageSpec.scala
  test/pages/regulatorsAndDocuments/CharityRegulatorPageSpec.scala
  test/pages/regulatorsAndDocuments/SelectGoverningDocumentPageSpec.scala
  test/pages/regulatorsAndDocuments/SelectWhyNoRegulatorPageSpec.scala
  test/repositoryMocks/MockSessionRepository.scala
  test/utils/Generators.scala
Labels: Approved

#67 DDCE-438: working can we send letters to this address page with summa…
  app/controllers/charityInformation/CanWeSendToThisAddressController.scala
  app/forms/charityInformation/CanWeSendToThisAddressFormProvider.scala
  app/navigation/CharityInformationNavigator.scala
  app/pages/charityInformation/CanWeSendToThisAddressPage.scala
  app/viewmodels/charityInformation/CharityInformationSummaryHelper.scala
  app/views/charityInformation/CanWeSendToThisAddressView.scala.html
  conf/charityInformation.routes
  conf/messages.cy
  conf/messages.en
  test/controllers/charityInformation/CanWeSendToThisAddressControllerSpec.scala
  test/forms/charityInformation/CanWeSendToThisAddressFormProviderSpec.scala
  test/navigation/CharityInformationNavigatorSpec.scala
  test/navigation/DocumentsNavigatorSpec.scala
  test/pages/charityInformation/CanWeSendToThisAddressPageSpec.scala
  test/viewModels/regulatorsAndDocuments/CharityInformationSummaryHelperSpec.scala
  test/views/charityInformation/CanWeSendToThisAddressViewSpec.scala
Labels: question
