Repository hmrc/charities-registration-frontend, pull requests merged in 2020-07, with the labels that each got.

#92 DDCE-762: Changes to bank details navigations
  app/controllers/IndexController.scala
  test/controllers/IndexControllerSpec.scala
Labels: Reviewing

#100 DDCE-817: Correction - Check your charity’s objectives details
  app/models/WithOrder.scala
  app/models/operations/CharitablePurposes.scala
  app/models/operations/FundRaisingOptions.scala
  app/models/operations/OperatingLocationOptions.scala
  app/models/regulators/CharityRegulator.scala
  app/viewmodels/CheckYourAnswersHelper.scala
  test/models/WithOrderSpec.scala
  test/models/operations/CharitablePurposesSpec.scala
  test/models/regulators/CharityRegulatorSpec.scala
  test/viewModels/operationsAndFunds/CharityObjectivesSummaryHelperSpec.scala
  test/viewModels/operationsAndFunds/OperationsFundsSummaryHelperSpec.scala
Labels: Approved

#99 DDCE-775:National Insurance number Question page
  app/controllers/authorisedOfficials/IsAuthorisedOfficialPositionController.scala
  app/forms/authorisedOfficials/IsAuthorisedOfficialPositionFormProvider.scala
  app/navigation/AuthorisedOfficialsNavigator.scala
  app/pages/authorisedOfficials/IsAuthorisedOfficialPositionPage.scala
  app/views/authorisedOfficials/IsAuthorisedOfficialPositionView.scala.html
  conf/messages.cy
  conf/messages.en
  conf/officialsAndNominees.routes
  test/controllers/authorisedOfficials/IsAuthorisedOfficialPositionControllerSpec.scala
  test/forms/authorisedOfficials/IsAuthorisedOfficialPositionFormProviderSpec.scala
  test/navigation/AuthorisedOfficialsNavigatorSpec.scala
  test/pages/authorisedOfficials/IsAuthorisedOfficialPositionPageSpec.scala
  test/views/authorisedOfficials/IsAuthorisedOfficialPositionViewSpec.scala
Labels: question

#104 DDCE-792: authorised official address lookup changes
  app/controllers/addressLookup/AuthorisedOfficialsAddressLookupController.scala
  app/controllers/authorisedOfficials/AuthorisedOfficialsDOBController.scala
  app/controllers/authorisedOfficials/AuthorisedOfficialsPhoneNumberController.scala
  app/models/addressLookup/AddressLookupLanguageModel.scala
  app/navigation/AuthorisedOfficialsNavigator.scala
  app/pages/addressLookup/AuthorisedOfficialAddressLookupPage.scala
  conf/address.routes
  conf/messages.cy
  conf/messages.en
  test/controllers/addressLookup/AuthroisedOfficialsAddressLookupControllerSpec.scala
  test/navigation/AuthorisedOfficialsNavigatorSpec.scala
  test/pages/addressLookup/AuthorisedOfficialsAddressPageSpec.scala
  test/pages/addressLookup/CharityOfficialAddressLookupPageSpec.scala
Labels: Reviewing

#108 removed service name from address lookup title messages
  conf/messages.cy
  conf/messages.en
Labels: Reviewing

#116 DDCE-815: changes for Check your charity’s nominee details
  app/controllers/nominees/NomineeDetailsSummaryController.scala
  app/navigation/NomineesNavigator.scala
  app/pages/nominees/NomineeDetailsSummaryPage.scala
  app/viewmodels/nominees/NomineeDetailsSummaryHelper.scala
  conf/messages.cy
  conf/messages.en
  conf/officialsAndNominees.routes
  test/controllers/nominees/NomineeDetailsSummaryControllerSpec.scala
  test/navigation/NomineesNavigatorSpec.scala
  test/pages/nominees/NomineeDetailsSummaryPageSpec.scala
  test/viewModels/nominees/NomineeDetailsSummaryHelperSpec.scala
Labels: Reviewing

#120 DDCE-861: changes for P4 Journey 1 - Changes to governing document details
  app/navigation/DocumentsNavigator.scala
  app/viewmodels/regulatorsAndDocuments/GoverningDocumentSummaryHelper.scala
  test/navigation/DocumentsNavigatorSpec.scala
  test/viewModels/regulatorsAndDocuments/GoverningDocumentSummaryHelperSpec.scala
Labels: Reviewing

#121 DDCE-866:Remove 'Check if you can register' tagline from all pages
  app/views/checkEligibility/IsEligibleAccountView.scala.html
  app/views/checkEligibility/IsEligibleLocationOtherView.scala.html
  app/views/checkEligibility/IsEligibleLocationView.scala.html
  app/views/checkEligibility/IsEligiblePurposeView.scala.html
  conf/messages.cy
  conf/messages.en
  test/views/checkEligibility/IsEligibleAccountViewSpec.scala
  test/views/checkEligibility/IsEligibleLocationOtherViewSpec.scala
  test/views/checkEligibility/IsEligibleLocationViewSpec.scala
  test/views/checkEligibility/IsEligiblePurposeViewSpec.scala
Labels: Reviewing

#126 Ddce 872:Not Eligible 1 Page
  app/controllers/checkEligibility/InEligibleCharitablePurposesController.scala
  app/navigation/EligibilityNavigator.scala
  app/views/checkEligibility/InEligibleCharitablePurposesView.scala.html
  conf/checkEligibility.routes
  conf/messages.cy
  conf/messages.en
  test/controllers/checkEligibility/InEligibleCharitablePurposesControllerSpec.scala
  test/navigation/EligibilityNavigatorSpec.scala
  test/views/checkEligibility/InEligibleCharitablePurposesViewSpec.scala
Labels: Reviewing

#133 DDCE-873:Not eligible second page
  app/controllers/checkEligibility/InEligibleBankController.scala
  app/navigation/EligibilityNavigator.scala
  app/views/checkEligibility/InEligibleBankView.scala.html
  conf/checkEligibility.routes
  conf/messages.cy
  conf/messages.en
  test/controllers/checkEligibility/InEligibleBankControllerSpec.scala
  test/navigation/EligibilityNavigatorSpec.scala
  test/views/checkEligibility/InEligibleBankViewSpec.scala
Labels: Reviewing

#141 DDCE-829: changes for P12 - You will be adding the second official in the next page
  app/controllers/otherOfficials/AddSecondOtherOfficialsController.scala
  app/navigation/OtherOfficialsNavigator.scala
  app/views/otherOfficials/AddSecondOtherOfficialsView.scala.html
  conf/messages.cy
  conf/messages.en
  conf/officialsAndNominees.routes
  test/controllers/otherOfficials/AddSecondOtherOfficialsControllerSpec.scala
  test/navigation/OtherOfficialsNavigatorSpec.scala
  test/views/otherOfficials/AddOtherOfficialsViewSpec.scala
Labels: Reviewing

#146 DDCE-931: changes for signout link
  app/config/FrontendAppConfig.scala
  app/views/templates/GovukLayoutWrapper.scala.html
  conf/application.conf
  test/config/FrontendAppConfigSpec.scala
Labels: Approved
