Repository hmrc/charities-registration-frontend, pull requests merged in 2021-02, with the labels that each got.

#391 DDCE-1416: Complete Remaining Integration Tests
  app/viewmodels/ErrorHandler.scala
  it/controllers/DeclarationControllerISpec.scala
  it/resources/scenario_4_request.json
  it/resources/scenario_4_transformed_request.json
  it/resources/scenario_5_request.json
  it/resources/scenario_5_transformed_request.json
  it/resources/scenario_6_request.json
  it/resources/scenario_6_transformed_request.json
  it/resources/scenario_7_request.json
  it/resources/scenario_7_transformed_request.json
  it/resources/transformed_request_for_min_data.json
  it/stubs/CharitiesStub.scala
  it/utils/IntegrationSpecBase.scala
Labels: Approved

#392 DDCE-1523: Merged the two submission audit events into one
  app/audit/DeclarationAuditEvent.scala
  app/audit/SubmissionAuditEvent.scala
  app/service/CharitiesRegistrationService.scala
  test/audit/AuditServiceSpec.scala
  test/service/CharitiesRegistrationServiceSpec.scala
Labels: Approved, DO NOT MERGE

#397 [DDCE-1573]:Implement new 'your answers have been lost' error page for switched-over users
  app/controllers/SwitchOverAnswersLostErrorController.scala
  app/service/CharitiesSave4LaterService.scala
  app/transformers/package.scala
  app/viewmodels/authorisedOfficials/AuthorisedOfficialsStatusHelper.scala
  app/viewmodels/otherOfficials/OtherOfficialStatusHelper.scala
  app/views/SwitchOverAnswersLostErrorView.scala.html
  conf/app.routes
  conf/messages.cy
  conf/messages.en
  test/controllers/SwitchOverAnswersLostErrorControllerSpec.scala
  test/service/CharitiesSave4LaterServiceSpec.scala
  test/transformers/CharitiesJsObjectSpec.scala
  test/views/SwitchOverAnswersLostErrorViewSpec.scala
Labels: Reviewing
